### ISSUE TITLE
Why `vmull_p64 ` was removed?

### ISSUE THREAD

**Issue by LuoZijun** [rust-lang/stdarch#1156]
the `aarch64` [vmull_p64](https://developer.arm.com/architectures/instruction-sets/simd-isas/neon/intrinsics?search=vmull_p64)  instruction seems to have been deleted in `nightly rust`. what happened?

Stable Rust: https://doc.rust-lang.org/core/arch/aarch64/fn.vmull_p64.html

**Comment by bjorn3** [comment]
This seems to be a combination of 0a658ba and 8fef044 from #1147. The first commit removed the aarch64 implementation and added one for both arm32 and aarch64. The second commit removed it for both architectures. LLVM supposedly doesn't actually support it for arm32: https://github.com/rust-lang/stdarch/pull/1147#discussion_r623549422 I think the second commit should have reverted back to the state before 0a658ba instead of removing it for both architectures.

**Comment by Amanieu** [comment]
cc @SparrowLii
