### ISSUE TITLE
neon vst1_* intrinsics copy many more bytes than they should.

### ISSUE THREAD

**Issue by HEnquist** [rust-lang/stdarch#1220]
This was introduces in this commit:
https://github.com/rust-lang/stdarch/commit/907cfb2ba01b23d2412c12a82994848300e29bbd

For example: https://github.com/rust-lang/stdarch/blob/89b0e355bc3cff5cddec2290c84f36eb3a026aad/crates/core_arch/src/aarch64/neon/mod.rs#L1129
```
pub unsafe fn vst1q_f64(ptr: *mut f64, a: float64x2_t) {
    copy_nonoverlapping(
        &a as *const float64x2_t as *const f64,
        ptr as *mut f64,
        size_of::<float64x2_t>(),
    )
}
```
The docs for copy_nonoverlapping says "Copies count * size_of::<T>() bytes from src to dst"
The example above will get called with type T = f64 (with size 8 bytes), and count = size_of::<float64x2_t> = 16. So it will end up copying 8*16=128 bytes. That's quite a bit more than the 16 bytes it should have been.
The result is that it writes garbage to memory locations it should not touch.

https://doc.rust-lang.org/core/ptr/fn.copy_nonoverlapping.html

**Comment by hkratz** [comment]
There is no instance of `copy_nonoverlapping()` remaining in the armv7/aarch64 intrinsics, so that all should be fixed in master, see e.g. https://github.com/rust-lang/stdarch/blob/5fdbc476afc81a789806697fc4a2d9d19b8c9993/crates/core_arch/src/aarch64/neon/mod.rs#L937-L939
But the stdarch submodule should be updated in the main Rust repo asap.

**Comment by HEnquist** [comment]
Ah thanks, the submodule thing threw me off. Let's keep this open then until the changes have made it into the main Rust repo.

**Comment by pthariensflame** [comment]
Seems like rust-lang/rust#89145 is now merged!
