### ISSUE TITLE
avx512gfni and avx512vaes feature names might be misleading

### ISSUE THREAD

**Issue by calebzulawski** [rust-lang/stdarch#1325]
I already opened rust-lang/rust#100752, but this might be the more relevant location.  More details are in the attached issue, but there exist CPUs that have GFNI and VAES without AVX-512, and Intel doesn't seem to classify them as part of AVX-512.  It might be better to name them simply `gfni` and `vaes`.

**Comment by SchrodingerZhu** [comment]
so as vpclmulqdq

**Comment by calebzulawski** [comment]
[Tremont](https://en.wikichip.org/wiki/intel/microarchitectures/tremont) supports GFNI with smaller vectors only.

**Comment by Amanieu** [comment]
I feel that issue should be discussed in https://github.com/rust-lang/rust/issues/100752 since feature names are defined in rustc, not stdarch. Once a decision has been made on that issue then we can make the necessary changes to stdarch. I expect the most likely resolution would be to add feature name aliases, since we need to keep the old names for backward compatibility.

**Comment by calebzulawski** [comment]
Sounds good to me.
