### ISSUE TITLE
Remove the MMX intrinsics

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang/stdarch#823]
This will need some motivation and rationale, but the TL;DR is that they are very hard to use correctly, and they cause subtle bugs that take a lot of people a lot of time to debug. They aren't in the path towards stabilization either, so those who really need them can migrate towards using inline assembly instead, which is just as unstable. 

We should probably phase in a deprecation warning first, and remove them some time later.

**Comment by rkruppe** [comment]
I would even argue they are *impossible* to use correctly in several circumstances:

- As discussed in https://github.com/rust-lang/rust/issues/53254#issuecomment-544915569, they break some libm functions on windows-gnu targets and `emm` can't reliably fix that.
- On x86 targets without SSE2, *any* float math will use the x87 stack, and for the same reason as in https://github.com/rust-lang/rust/issues/53254#issuecomment-544915569, `emms` can be reordered across those operations.

So if you're on one of these targets, and use certain operations on floats anywhere in the program, you're basically entirely at the mercy of LLVM not getting too aggressive with reordering code.

**Comment by mati865** [comment]
LLVM developers are wondering about removing MMX: https://www.phoronix.com/scan.php?page=news_item&px=LLVM-Goodbye-MMX-Maybe

**Comment by Amanieu** [comment]
It seems that LLVM's main concern is backwards compatibility with existing code that uses `__m64` and MMX intrinsics. We don't have this concern in Rust because there is no existing (stable) code using MMX.

I propose simply removing the MMX intrinsics and MMX types. I don't think there is much value in emulating them on top of SSE2 since anyone writing new code should not be using MMX intrinsics.

Note that there is still an issue with inline asm in that it can't properly express clobbers of the FP/MMX registers, so you currently can't use it with MMX instructions.

**Comment by lu-zero** [comment]
Sounds a good idea given the potential harm.

**Comment by mati865** [comment]
I could prepare PR but what to do with `is_x86_feature_detected!("mmx")`?
It's currently works on stable: https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=41534dce6ad51df68df2e79323adfd44

**Comment by Amanieu** [comment]
It's fine to have feature detection for a feature even if we don't support codegen for it.
